name: epic-app
services:
  - name: web
    source_dir: /
    github:
      repo: your-username/do-epicapp
      branch: main
    run_command: npm start
    build_command: npm run build:deploy
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /
    health_check:
      http_path: /resources/healthcheck
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        type: SECRET
      - key: DATABASE_PATH
        value: /tmp/sqlite.db
      - key: SESSION_SECRET
        value: ${SESSION_SECRET}
        type: SECRET
      - key: INTERNAL_COMMAND_TOKEN
        value: ${INTERNAL_COMMAND_TOKEN}
        type: SECRET
      - key: HONEYPOT_SECRET
        value: ${HONEYPOT_SECRET}
        type: SECRET
      - key: CACHE_DATABASE_PATH
        value: /tmp/cache.db
      - key: AWS_ACCESS_KEY_ID
        value: ${AWS_ACCESS_KEY_ID}
        type: SECRET
      - key: AWS_SECRET_ACCESS_KEY
        value: ${AWS_SECRET_ACCESS_KEY}
        type: SECRET
      - key: AWS_REGION
        value: ${AWS_REGION}
      - key: AWS_ENDPOINT_URL_S3
        value: ${AWS_ENDPOINT_URL_S3}
      - key: BUCKET_NAME
        value: ${BUCKET_NAME}
      - key: RESEND_API_KEY
        value: ${RESEND_API_KEY}
        type: SECRET
      - key: GITHUB_CLIENT_ID
        value: ${GITHUB_CLIENT_ID}
        type: SECRET
      - key: GITHUB_CLIENT_SECRET
        value: ${GITHUB_CLIENT_SECRET}
        type: SECRET
      - key: GITHUB_REDIRECT_URI
        value: ${GITHUB_REDIRECT_URI}
      - key: GITHUB_TOKEN
        value: ${GITHUB_TOKEN}
        type: SECRET
      - key: ALLOW_INDEXING
        value: "true"

databases:
  - name: db
    engine: PG
    version: "15"
    production: false
    size: db-s-1vcpu-1gb 